### ISSUE TITLE
[Linux] desktop file is lacking a Categories= entry

### ISSUE THREAD

**Issue by probonopd** [LucaT1/yat#58]
The desktop file is lacking a `Categories=` entry in the `*.desktop` file.

According to the [menu spec](https://standards.freedesktop.org/menu-spec/latest/apa.html),

> By including one of the Main Categories in an application's desktop entry file, the application will be ensured that it will show up in a section of the application menu dedicated to this category. If multiple Main Categories are included in a single desktop entry file, the entry may appear more than once in the menu. 

Hence, please add at least one of the following in the `Categories=` key.

Main Category | Description | Notes
-- | -- | --
AudioVideo | Application for presenting, creating, or processing multimedia (audio/video) |  
Audio | An audio application | Desktop entry must include AudioVideo as well
Video | A video application | Desktop entry must include AudioVideo as well
Development | An application for development |  
Education | Educational software |  
Game | A game |  
Graphics | Application for viewing, creating, or processing graphics |  
Network | Network application such as a web browser |  
Office | An office type application |  
Science | Scientific software |  
Settings | Settings applications | Entries may appear in a separate menu or as part of a 		"Control Center"
System | System application, "System Tools" such as say a log viewer or network monitor |  
Utility | Small utility application, "Accessories"

In addition, you could specify one or more from the longer list of [Additional Categories](https://standards.freedesktop.org/menu-spec/latest/apas02.html).

Please test the result with `desktop-file-validate` and make sure it passes.

electron-builder offers native support for this since [v19.22.1](https://github.com/electron-userland/electron-builder/releases/tag/v19.22.1).

Reference: https://github.com/AppImage/AppImageHub/issues/2

**Comment by lucat1** [comment]
Thanks for the catch @probonopd,
I've seen that feature in the electron-builder's changelog and as a Linux user, I believe it definitely needs to be implemented. This would be :top: in an environment like Ubuntu's Unity DE, Gnome and such. I didn't notice it since I use bspwm and doesn't make any difference with dmenu.

Since it's an easy one I'll make some commits and fix it in a few hours. 
Minor fix release should be available very soon!

**Comment by lucat1** [comment]
Should be fixed in master. Scheduling new minor release! :tada:

**Comment by lucat1** [comment]
Okay so as you can see builds are failing with an fpm error, that I couldn't figure out why is happening. 
Here's [a stack trace](https://travis-ci.org/vterm/vterm/jobs/267267598). It would be cool if you could give me some hints, otherwise I'll report it to electron-builder.

For now, I'll remove the deb target, but it's a huge debt.
/ping @probonopd

**Comment by probonopd** [comment]
I don't know why the tar process fails. Try rerunning, and if the problem persists please ping electron-builder developer _develar_.

**Comment by lucat1** [comment]
Yep i've already tried re-running, so i'll ping him:
/ping @develar

**Comment by develar** [comment]
@LucaT1 Please set env DEBUG=electron-builder in the travis settings and restart build.

**Comment by lucat1** [comment]
I'll try sure. Thanks.

EDIT:
Done, you can check out #59 for more info. I'd like to move the discussion there which seems more appropriate.

/ping @develar
